# Generated by Django 6.0 on 2025-12-24 07:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('service_type_enum', models.PositiveSmallIntegerField(choices=[(101, 'Первичная консультация терапевта'), (102, 'Повторная консультция терапевта'), (103, 'Профилактический осмотр'), (104, 'Расшифровка анализов'), (105, 'Выдача справки/больничного'), (106, 'Вакцинация'), (107, 'ЭКГ с расшифровкой'), (108, 'Измерение давления/пульса'), (109, 'Составление плана лечения'), (201, 'Первичная консультация кардиолога'), (202, 'Повторная консультация кардиолога'), (203, 'Суточный мониторинг ЭКГ'), (204, 'Эхокардиограмма (УЗИ сердца)'), (205, 'Нагрузочные тесты'), (206, 'Подбор гипотензивной терапии'), (301, 'Консультация невролога'), (302, 'ЭЭГ'), (303, 'УЗИ сосудов шеи/головы'), (304, 'Блокада при остеохондрозе'), (305, 'Лечение мигрени'), (306, 'Рефлексотерапия'), (401, 'Консултация стоматолога'), (402, 'Профессиональная гигиена'), (403, 'Лечение кариеса'), (404, 'Удаление зуба простое'), (405, 'Удаление зуба сложное'), (406, 'Отбеливание зубов'), (407, 'Установка пломбы световой'), (501, 'Консультация офтальмолога'), (502, 'Подбор очков/линз'), (503, 'Измерение внутриглазного давления'), (504, 'Осмотр глазного дна'), (505, 'Лечение конъюнктивита'), (601, 'Консультация дерматолога'), (602, 'Удаление родинки/папилломы'), (603, 'Лечение акне'), (604, 'Криодеструкция'), (605, 'Биопсия кожи'), (701, 'Консультация педиатра'), (702, 'Патронаж новорожденного'), (703, 'Вакцинация по календарю'), (704, 'Осмотр перед садом/школой'), (801, 'Консультация хирурга'), (802, 'Перевязка'), (803, 'Вскрытие абсцесса'), (804, 'Наложение швов'), (805, 'Удаление вросшего ногтя'), (901, 'Консультация психолога'), (902, 'Сеанс психотерапии'), (903, 'Подбор антидепрессантов'), (904, 'Семейная консультация'), (1001, 'Консультация гинеколога'), (1002, 'УЗИ органов малого таза'), (1003, 'Взятие мазков'), (1004, 'Установка/снятие ВМС'), (1101, 'Общий анализ крови'), (1102, 'Биохимический анализ крови'), (1103, 'УЗИ брюшной полости'), (1104, 'Рентген грудной клетки'), (1105, 'МРТ/КТ (консультация по результатам)'), (1201, 'Онлайн-консультация'), (1202, 'Вызов врача на дом'), (1203, 'Забор анализов на дому'), (1204, 'Медицинская документация')], verbose_name='Вид услуги')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Стоимость услуги',
                'verbose_name_plural': 'Стоимость услуг',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=125, verbose_name='Название')),
                ('client_notes', models.TextField(blank=True, max_length=500, verbose_name='Запись клиента')),
                ('specialist_notes', models.TextField(blank=True, max_length=500, verbose_name='Запись специалиста')),
                ('status_enum', models.PositiveSmallIntegerField(choices=[(200, 'Активна'), (300, 'Забронирована'), (400, 'Выполняется'), (500, 'Завершена'), (600, 'Отменена')], verbose_name='Статус бронирования')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='employee.client', verbose_name='Клиент')),
                ('specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='employee.specialist', verbose_name='Специалист')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='appointment.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость услуги')),
                ('status_enum', models.PositiveSmallIntegerField(choices=[(1, 'Ожидает'), (2, 'Оплачен'), (3, 'Возврат')], default=1, verbose_name='Статус оплаты')),
                ('payment_method', models.CharField(max_length=125, verbose_name='Метод оплаты')),
                ('transaction_id', models.CharField(blank=True, max_length=128, verbose_name='id транзакции')),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='appointment.appointment', verbose_name='Бронь')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплата',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Рейтинг')),
                ('comment', models.TextField(validators=[django.core.validators.MaxLengthValidator(510)], verbose_name='Комментарий')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опуликовано')),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='appointment.appointment', verbose_name='Бронь')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='employee.client', verbose_name='Клиент')),
                ('specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='employee.specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('schedule_type', models.PositiveSmallIntegerField(choices=[(1, 'Регулярное'), (2, 'Разовое')], default=1, verbose_name='Тип расписания')),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], null=True, verbose_name='День недели')),
                ('start_at', models.TimeField(verbose_name='Время начала')),
                ('end_at', models.TimeField(verbose_name='Время окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='employee.specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='servie_price',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='appointment.serviceprice', verbose_name='Стоимость услуги'),
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('start_at', models.DateTimeField(verbose_name='Начало в')),
                ('end_at', models.DateTimeField(verbose_name='Окончание в')),
                ('status_enum', models.PositiveSmallIntegerField(choices=[(1, 'Свободен'), (2, 'Забронирован'), (3, 'Отменен')], default=1, verbose_name='Статус слота')),
                ('service_type_enum', models.PositiveSmallIntegerField(choices=[(101, 'Первичная консультация терапевта'), (102, 'Повторная консультция терапевта'), (103, 'Профилактический осмотр'), (104, 'Расшифровка анализов'), (105, 'Выдача справки/больничного'), (106, 'Вакцинация'), (107, 'ЭКГ с расшифровкой'), (108, 'Измерение давления/пульса'), (109, 'Составление плана лечения'), (201, 'Первичная консультация кардиолога'), (202, 'Повторная консультация кардиолога'), (203, 'Суточный мониторинг ЭКГ'), (204, 'Эхокардиограмма (УЗИ сердца)'), (205, 'Нагрузочные тесты'), (206, 'Подбор гипотензивной терапии'), (301, 'Консультация невролога'), (302, 'ЭЭГ'), (303, 'УЗИ сосудов шеи/головы'), (304, 'Блокада при остеохондрозе'), (305, 'Лечение мигрени'), (306, 'Рефлексотерапия'), (401, 'Консултация стоматолога'), (402, 'Профессиональная гигиена'), (403, 'Лечение кариеса'), (404, 'Удаление зуба простое'), (405, 'Удаление зуба сложное'), (406, 'Отбеливание зубов'), (407, 'Установка пломбы световой'), (501, 'Консультация офтальмолога'), (502, 'Подбор очков/линз'), (503, 'Измерение внутриглазного давления'), (504, 'Осмотр глазного дна'), (505, 'Лечение конъюнктивита'), (601, 'Консультация дерматолога'), (602, 'Удаление родинки/папилломы'), (603, 'Лечение акне'), (604, 'Криодеструкция'), (605, 'Биопсия кожи'), (701, 'Консультация педиатра'), (702, 'Патронаж новорожденного'), (703, 'Вакцинация по календарю'), (704, 'Осмотр перед садом/школой'), (801, 'Консультация хирурга'), (802, 'Перевязка'), (803, 'Вскрытие абсцесса'), (804, 'Наложение швов'), (805, 'Удаление вросшего ногтя'), (901, 'Консультация психолога'), (902, 'Сеанс психотерапии'), (903, 'Подбор антидепрессантов'), (904, 'Семейная консультация'), (1001, 'Консультация гинеколога'), (1002, 'УЗИ органов малого таза'), (1003, 'Взятие мазков'), (1004, 'Установка/снятие ВМС'), (1101, 'Общий анализ крови'), (1102, 'Биохимический анализ крови'), (1103, 'УЗИ брюшной полости'), (1104, 'Рентген грудной клетки'), (1105, 'МРТ/КТ (консультация по результатам)'), (1201, 'Онлайн-консультация'), (1202, 'Вызов врача на дом'), (1203, 'Забор анализов на дому'), (1204, 'Медицинская документация')], verbose_name='Вид услуги')),
                ('specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_slot', to='employee.specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Слот',
                'verbose_name_plural': 'Слоты',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_slot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='appointment.timeslot', verbose_name='Слот'),
        ),
    ]
