# Generated by Django 6.0 on 2025-12-24 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileClient',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('photo', models.ImageField(blank=True, upload_to='photo_base_profile/', verbose_name='Фото')),
                ('first_booking_date', models.DateTimeField(auto_now_add=True, verbose_name='Первое бронирование')),
            ],
            options={
                'verbose_name': 'Профиль клиента',
                'verbose_name_plural': 'Профили клиентов',
            },
        ),
        migrations.CreateModel(
            name='SpecialistProfessionalInfo',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization_enum', models.PositiveSmallIntegerField(choices=[(0, 'Терапевт(общая)'), (1, 'Кардиолог'), (2, 'Невролог'), (3, 'Дерматолог'), (4, 'Стоматолог'), (5, 'Педиатр'), (6, 'Хирург'), (7, 'Психолог'), (8, 'Гинеколог'), (9, 'Офтальмолог')], default=0, verbose_name='Специализация')),
                ('education_enum', models.PositiveSmallIntegerField(choices=[(0, 'Среднее профессиональное'), (1, 'Неоконченное высшее'), (2, 'Бакалавр'), (3, 'Специалист'), (4, 'Магистр'), (5, 'Аспирантура'), (6, 'Докторнатура'), (7, 'MBA')], default=3, verbose_name='Образование')),
                ('work_exp', models.PositiveIntegerField(default=0, verbose_name='Опыт работы')),
            ],
            options={
                'verbose_name': 'Профессиональные данные',
                'verbose_name_plural': 'Профессиональные данные',
            },
        ),
        migrations.CreateModel(
            name='SpecialistSettings',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_add', models.BooleanField(default=True, verbose_name='Принимает новый клиентов')),
                ('time_to_answer', models.PositiveIntegerField(default=2, verbose_name='Время ответа на запрос')),
                ('auto_confirm', models.BooleanField(default=False, verbose_name='Автоподтверждение')),
            ],
            options={
                'verbose_name': 'Настройки специалиста',
                'verbose_name_plural': 'Настройки специалиста',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='employee.profileclient', verbose_name='Профиль клиента')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='SpecialistProfile',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('photo', models.ImageField(blank=True, upload_to='photo_base_profile/', verbose_name='Фото')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Рейтинг')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='Количество отзывов')),
                ('prof_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='employee.specialistprofessionalinfo', verbose_name='Профессиональные данные')),
                ('settings', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='employee.specialistsettings', verbose_name='Настройки')),
            ],
            options={
                'verbose_name': 'Профиль специалиста',
                'verbose_name_plural': 'Профили специалистов',
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialists', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specialists', to='employee.specialistprofile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
            },
        ),
    ]
